---
- name: Create clsuters
  include: create.yml
  when: not destory_stack|d(False)
  tags:
    - ecs

- name: Destroy ecs clusters
  include: destroy.yml
  when: destory_stack|d(False)
  tags:
    - ecs
