---
- name: Create clsuters
  include: create.yml
  when: not destroy_stack|d(False)
  tags:
    - ecs

- name: Destroy ecs clusters
  include: destroy.yml
  when: destroy_stack|d(False)
  tags:
    - ecs
