---
- set_fact:
    ecs_clusters: "{{ app_data|rejectattr('ecs_cluster', 'undefined')|map(attribute='ecs_cluster')|list|unique }}"

- name: Ensure clusters are created
  ecs_cluster:
    name: "{{ item }}"
    state: present
  register: cluster_data
  with_items: "{{ ecs_clusters }}"

