---

- name: Get account id data
  shell: aws iam list-users --output json | grep Arn | cut -d ':' -f 6 | uniq
  register: account_id
  always_run: true
  no_log: true
  tags:
    - always

- name: Make accountid value available
  set_fact:
    aws_acc_id: "{{ account_id.stdout }}"
  always_run: true
  no_log: true
  tags:
    - always
