---
#get some data from the shared vpc
- name:  Get vpc data for stack
  ec2_vpc_net_facts:
    filters:
      'tag:Name': "{{ [vpc_name, opg_data.domain]|join('.') }}"
  register: vpc_data

- name: Get list of subnets
  ec2_vpc_subnet_facts:
    filters:
      vpc-id: "{{ vpc_data.vpcs.0.id }}"
  register: subnet_data

- name: Get account id data
  shell: aws iam list-users | grep Arn | cut -d ':' -f 6 | uniq
  register: account_id

- name: Make accountid value available
  set_fact:
    aws_acc_id: "{{ account_id.stdout }}"

- name: Setup vars for playbook
  set_fact:
    private_subnets: "{{ subnet_data.subnets | selectattr('tags.Name', 'match', '^private.*')| map(attribute='id') | list }}"
    public_subnets: "{{ subnet_data.subnets | selectattr('tags.Name', 'match', '^public.*')| map(attribute='id') | list }}"
    vpc_id: "{{ vpc_data.vpcs.0.id }}"

- name: Create core stack components
  include: network.yml

- name: Create dynamodb resources
  include: dynamodb.yml
  when: dynamodbs is defined

- name: Create sns resources
  include: sns.yml
  when: sns_topics is defined

- name: Create s3 resources
  include: s3.yml
  when: s3_buckets is defined

- name: Create rds resources
  include: rds.yml
  when: rds_dbs is defined

- name: Create elasticache resources
  include: elasticache.yml
  with_items: "{{ elasticache_clusters | default([]) }}"
  loop_control:
    loop_var: ec_data
  when: elasticache_clusters is defined

- name: Create IAM resources
  include: iam.yml
  when: iam_policy_data is defined

- name: Create infrastructure for app
  include: infra.yml
  with_items: "{{ app_data |default([]) }}"
  loop_control:
    loop_var: appdata

