---
- name: Create S3 buckets
  s3_bucket:
    name: "{{ [item.name, opg_data.stack]|join('-') }}"
    state: present
#    permission: private
    policy: "{{ lookup('template','s3_bucket_policy.json') | to_json }}"
  with_items: "{{ s3_buckets | default([]) }}"
  register: s3_bucket_created

