---
- name: Create S3 buckets
  s3:
    bucket: "{{ [item.name, opg_data.stack]|join('-') }}"
    mode: create
    permission: private
  with_items: "{{ s3_buckets | default([]) }}"
  register: s3_bucket_created

