---

- name: Create sns topics
  sns_topic:
    name: "{{ [item, opg_data.shared_resource_suffix]|join('-') }}"
    state: present
    display_name: "{{ [item, opg_data.shared_resource_suffix]|join('-') }}"
  with_items: "{{ sns_topics|default([]) }}"
  register: sns_topics_created

- debug:
    msg: "{{ sns_topics_created.results }}"

