---
- name: Create sns topics
  sns_topic:
    name: "{{ [item, opg_data.stack]|join('-') }}"
    state: present
    display_name: "{{ [item, opg_data.stack]|join('-') }}"
  with_items: "{{ sns_topics|default([]) }}"
  register: sns_topics_created
