---
- name: Create iam role
  iam:
    iam_type: role
    name: '{{ item }}-role-{{ opg_data.stack }}'
    state: present
    trust_policy:
      Version: '2012-10-17'
      Statement:
      - Action: sts:AssumeRole
        Effect: Allow
        Principal:
          Service: ec2.amazonaws.com
  with_items: "{{ vpc.iam_roles }}"

- name: Create common iam policy
  iam_policy:
    state: present
    policy_name: 'common-policy-{{ opg_data.stack }}'
    iam_type: role
    iam_name: '{{ item }}-role-{{ opg_data.stack }}'
    policy_json: " {{ lookup('file', 'common.iam.policy') }} "
  with_items: "{{ vpc.iam_roles }}"

#- name: Create monitoring iam policy
#  iam_policy:
#    state: present
#    policy_name: 'monitoring-policy-{{ opg_data.stack }}'
#    iam_type: role
#    iam_name: 'monitoring-role-{{ opg_data.stack }}'
#    policy_json: " {{ lookup('file', 'monitoring.iam.policy') }} "
