---
#print debug information
- block:
    - name: Include debug play
      include: debug.yml
    - name: Pause to reflect on the debug messages
      pause:
        minutes: 2
  when: "{{ debug | default(False)}}"
  tags:
    - debug

#create base vpc objects
- block:
  - name: Create VPC and networks
    include: network.yml
    tags:
      - network

  - name: Create security groups
    include: sg.yml
    tags:
      - security

  - name: Create base iam roles
    include: iam.yml
    tags:
      - iam

  - name: Add jumphost
    include: jump-host.yml
    tags:
      - instances
      - jumphost

  - name: Add master host
    include: master-host.yml
    tags:
      - master

  - name: Add monitoring host
    include: monitoring-host.yml
    tags:
      - monitoring

  when: "{{ vpc.state | default('present') == 'present' }}"

#cleanup/delete vpc
- block:
  - name: Delete VPC
    include: delete-vpc.yml
  when: "{{ vpc.state | default('present') == 'absent' }}"
  tags:
    - destroy
