---
- block:
    - name: Run destroy tasks to remove stack
      include: destroy_vpc.yml
  when: destroy_stack|default(False)|bool
  tags:
    - destroy

#create base vpc objects
- block:
  - name: Check for existing VPC
    ec2_vpc_net_facts:
      filters:
        'tag:Name': '{{ opg_data.stack }}.{{ opg_data.domain }}'
    register: vpc_check

  - name: Compare tags
    assert:
      that:
        - "vpc_check.vpcs.0.tags == vpc.env_tags|combine({'Name': opg_data.stack + '.' + opg_data.domain })"
    when: vpc_check.vpcs|count == 1

  - name: Create VPC and networks
    include: network.yml
    tags:
      - network

  - name: Create security groups
    include: sg.yml
    tags:
      - security

  - name: Create base iam roles
    include: iam.yml
    tags:
      - iam

  - name: Add jumphost
    include: jump-host.yml
    tags:
      - instances
      - jumphost

  - name: Add master host
    include: master-host.yml
    tags:
      - master

  when: destroy_stack is undefined or not destroy_stack|bool
