- name: Get a list of cluster arns
  command: "aws ecs list-clusters --output json"
  register: ecs_cluster_arns

- name: Get a list of our clusters
  command: "aws ecs describe-clusters --cluster {{ item }} --output json"
  register: ecs_cluster
  with_items: "{{ ecs_cluster_arns.stdout.clusterArns | split_part(1, '/') | default([]) }}"

- name: Get container instances as a list
  command: "aws ecs list-container-instances --cluster {{ item }} --output json"
  register: cluster_container_instances
  with_items: "{{ ecs_cluster_arns.stdout.clusterArns | split_part(1, '/') | default([]) }}"

